name: Cypress Tests

on:
  schedule:
    - cron: '0 10 * * *'  # Runs every day at 10 AM UTC
  push:

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
